### ISSUE TITLE
Running tests for celery causes issue: RuntimeError: Never call result.get() within a task!

### ISSUE THREAD

**Issue by ankitchiplunkar** [analyseether/ether_sql#31]
**Describe the bug**
To run tests for parallel processes we need to run celery processes in parallel. and then launch the tests.
Unfortunately this is not possible because we get the error 
```
================================================================== FAILURES ===================================================================
________________________________________________ test_infura_push_block_range_multiple_threads ________________________________________________

infura_settings = 'TestSettings'

    def test_infura_push_block_range_multiple_threads(infura_settings):
        celery_worker_thread = CeleryWorkerThread(app, settings=infura_settings)
        celery_worker_thread.setDaemon(True)
        celery_worker_thread.start()
        celery_worker_thread.ready.wait()
>       push_block_range_multiple_threads(infura_settings)

tests/infura/test_celery.py:13: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/common_tests/celery.py:35: in push_block_range_multiple_threads
    result.get()
venv/lib/python3.5/site-packages/celery/result.py:170: in get
    assert_will_not_block()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    def assert_will_not_block():
        if task_join_will_block():
>           raise RuntimeError(E_WOULDBLOCK)
E           RuntimeError: Never call result.get() within a task!
E           See http://docs.celeryq.org/en/latest/userguide/tasks.html#task-synchronous-subtasks

venv/lib/python3.5/site-packages/celery/result.py:41: RuntimeError
```

**To Reproduce**
1. `python -m pytest tests/infura/test_celery.py`

**Expected behavior**
The tests should run normally

**Additional context**
There are two different locations where a celery fixture starts in separate thread runs the tests and quits.
1. https://github.com/RentMethod/celerytest
2. https://github.com/celery/celery/blob/a3c377474ab1109a26de5169066a4fae0d30524b/celery/contrib/pytest.py 

The thing which is different in our case is that we need to start the celery with an `ether_sql_session` in the main thread.

**Comment by ankitchiplunkar** [comment]
This causes the following error when we switch on celery after running `test_celery.py`

```
[2018-06-14 18:11:02,534][PID:7286][ERROR][ForkPoolWorker-1] Task ether_sql.tasks.scrapper.add_block_number[e5cfecd1-7a2d-45a4-a93c-309f3bc1b7af] raised unexpected: ProgrammingError('(psycopg2.ProgrammingError) relation "blocks" does not exist\nLINE 1: INSERT INTO blocks (block_number, block_hash, parent_hash, d...\n                    ^\n',)
Traceback (most recent call last):
  File "/home/ankit/projects/ether_sql/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/home/ankit/projects/ether_sql/venv/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: relation "blocks" does not exist
LINE 1: INSERT INTO blocks (block_number, block_hash, parent_hash, d...
                    ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ankit/projects/ether_sql/venv/lib/python3.5/site-packages/celery/app/trace.py", line 375, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/ankit/projects/ether_sql/venv/lib/python3.5/site-packages/celery/app/trace.py", line 632, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/ankit/projects/ether_sql/ether_sql/tasks/scrapper.py", line 108, in add_block_number
    meta_info = current_session.db_session.query(MetaInfo).first()
  File "/home/ankit/projects/ether_sql/venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2778, in first
    ret = list(self[0:1])
  File "/home/ankit/projects/ether_sql/venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2570, in __getitem__
    return list(res)
  File "/home/ankit/projects/ether_sql/venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2877, in __iter__
    self.session._autoflush()
  File "/home/ankit/projects/ether_sql/venv/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 1444, in _autoflush
    util.raise_from_cause(e)
  File "/home/ankit/projects/ether_sql/venv/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/ankit/projects/ether_sql/venv/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/home/ankit/projects/ether_sql/venv/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 1434, in _autoflush
    self.flush()
  File "/home/ankit/projects/ether_sql/venv/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2243, in flush
    self._flush(objects)
  File "/home/ankit/projects/ether_sql/venv/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2369, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/ankit/projects/ether_sql/venv/lib/python3.5/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/ankit/projects/ether_sql/venv/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/home/ankit/projects/ether_sql/venv/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2333, in _flush
    flush_context.execute()
  File "/home/ankit/projects/ether_sql/venv/lib/python3.5/site-packages/sqlalchemy/orm/unitofwork.py", line 391, in execute
    rec.execute(self)
  File "/home/ankit/projects/ether_sql/venv/lib/python3.5/site-packages/sqlalchemy/orm/unitofwork.py", line 556, in execute
    uow
  File "/home/ankit/projects/ether_sql/venv/lib/python3.5/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/home/ankit/projects/ether_sql/venv/lib/python3.5/site-packages/sqlalchemy/orm/persistence.py", line 830, in _emit_insert_statements
    execute(statement, multiparams)
  File "/home/ankit/projects/ether_sql/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/home/ankit/projects/ether_sql/venv/lib/python3.5/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/ankit/projects/ether_sql/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/ankit/projects/ether_sql/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/home/ankit/projects/ether_sql/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/home/ankit/projects/ether_sql/venv/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/ankit/projects/ether_sql/venv/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/home/ankit/projects/ether_sql/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/home/ankit/projects/ether_sql/venv/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (psycopg2.ProgrammingError) relation "blocks" does not exist
LINE 1: INSERT INTO blocks (block_number, block_hash, parent_hash, d...
                    ^
 [SQL: 'INSERT INTO blocks (block_number, block_hash, parent_hash, difficulty, gas_used, miner, timestamp, sha3uncles, extra_data, gas_limit, uncle_count, transaction_count) VALUES (%(block_number)s, %(block_hash)s, %(parent_hash)s, %(difficulty)s, %(gas_used)s, %(miner)s, %(timestamp)s, %(sha3uncles)s, %(extra_data)s, %(gas_limit)s, %(uncle_count)s, %(transaction_count)s)'] [parameters: {'extra_data': '0x59617465732052616e64616c6c202d2045746865724e696e6a61', 'miner': '0xc8ebccC5F5689Fa8659d83713341e5aD19349448', 'timestamp': '2015-07-30T15:27:57', 'transaction_count': 0, 'block_number': 4, 'uncle_count': 1, 'gas_used': 0, 'parent_hash': '0x3d6122660cc824376f11ee842f83addc3525e2dd6756b9bcf0affa6aa88cf741', 'difficulty': 17146339321, 'gas_limit': 5000, 'sha3uncles': '0x83a8da8965660cb6bdf0c37f1b111778e49753c4213bf7c3e280fccfde89f2b5', 'block_hash': '0x23adf5a3be0f5235b36941bcb29b62504278ec5b9cdfa277b992ba4a7a3cd3a2'}] (Background on this error at: http://sqlalche.me/e/f405)
```
